# Generated by Django 3.1.1 on 2021-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='external_id',
            field=models.CharField(max_length=100),
        ),
    ]
