# Generated by Django 3.1.1 on 2021-10-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0003_content_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='notion.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('title', 'title'), ('rich_text', 'rich_text')], default='title', max_length=20),
        ),
    ]
